# Generates src/steamtables.js from IAPWS-IF97 (python `iapws` package).
import math
from iapws import IAPWS97

def r(x, n=6):
    return float(f"{x:.{n}g}")

# Saturation table, log-spaced in pressure (MPa)
NS = 140
pmin, pmax = 0.002, 21.0
sat = []
for i in range(NS):
    p = math.exp(math.log(pmin) + (math.log(pmax) - math.log(pmin)) * i / (NS - 1))
    f = IAPWS97(P=p, x=0); g = IAPWS97(P=p, x=1)
    sat.append([r(p), r(f.T - 273.15), r(f.rho), r(g.rho), r(f.h), r(g.h), r(f.s), r(g.s)])

# Superheated grid h(p,T), s(p,T); below saturation -> saturated vapour values
NP = 36
P = [r(math.exp(math.log(0.002) + (math.log(21.0) - math.log(0.002)) * i / (NP - 1))) for i in range(NP)]
T = list(range(20, 661, 10))
H, S, V = [], [], []
for p in P:
    ts = IAPWS97(P=p, x=1).T - 273.15
    hr, sr, vr = [], [], []
    for t in T:
        if t <= ts + 0.01:
            g = IAPWS97(P=p, x=1)
        else:
            g = IAPWS97(P=p, T=t + 273.15)
        hr.append(r(g.h, 6)); sr.append(r(g.s, 6)); vr.append(r(g.rho, 6))
    H.append(hr); S.append(sr); V.append(vr)

with open("../src/steamtables.js", "w") as fo:
    fo.write("// Generated by tools/gen_steam_tables.py from IAPWS-IF97. Units: MPa, degC, kg/m3, kJ/kg, kJ/kg/K.\n")
    fo.write("// SAT rows: [p, Tsat, rho_f, rho_g, h_f, h_g, s_f, s_g]\n")
    fo.write("export const SAT = " + str(sat).replace(" ", "") + ";\n")
    fo.write("export const SH_P = " + str(P).replace(" ", "") + ";\n")
    fo.write("export const SH_T = " + str(T).replace(" ", "") + ";\n")
    fo.write("export const SH_H = " + str(H).replace(" ", "") + ";\n")
    fo.write("export const SH_S = " + str(S).replace(" ", "") + ";\n")
    fo.write("export const SH_RHO = " + str(V).replace(" ", "") + ";\n")
print("ok")
